### ISSUE TITLE
Práctica de login Front End

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/practica-de-mockup-y-front-end-egal#2]
[Práctica de login  Front End.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-mockup-y-front-end-egal/files/6557676/Practica.de.login.Front.End.pdf)

**Comment by MariaC232** [comment]
Calificación: 28%
Buen trabajo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
